### ISSUE TITLE
Benchmark classes static method vs class method

### ISSUE THREAD

**Issue by NeoChaos12** [automl/HPOlib3#18]
I am working on introducing a fidelity space for the XGBoost benchmark, and potentially all benchmarks in general, and was wondering if there is a specific, obscure reason why some methods such as `get_configuration_space()` and `get_meta_information()` carry the `@staticmethod` decorator instead of `@classmethod`, and if it makes a difference if the methods I intend to write carry one or the other decorator. While this doesn't really make a difference for most wrapper functions, in these particular functions (as well as corresponding fidelity space functions that I am going to write) it might be useful to have direct access to the calling class object, especially from the perspective of establishing inheritance and the ability to overwrite methods. Case in point, I intended to write a `get_fidelity_space()` as well as a `get_fidelities()` method, such that the former returns a `ConfigurationSpace` object and the latter a `dict`. `get_fidelities()` would then like to have access to `get_fidelity_space()`, and a class method is slightly better suited for doing so. Perhaps @PhMueller would know this best?

**Comment by KEggensperger** [comment]
We have the `@staticmethod` because these methods do not need the class to be instantiated (which could be expensive, if it loads a large dataset). Therefore `get_fidelity_space()` should also be a `@staticmethod`. 

I don't think we need a `get_fidelities()` method for now since we can easily iterate over a ConfigurationSpace object. If there is a case where this is impossible, we can add it later on. In this case `get_fidelities()` could also call the staticmethod without requiring access to self.

**Comment by NeoChaos12** [comment]
I understand, thanks for the clarification!
